//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunActivityApp.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizUserAnswer
    {
        public int SubmissionID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public Nullable<int> AnswerID { get; set; }
        public Nullable<bool> IsRight { get; set; }
        public Nullable<System.DateTime> AnswerTime { get; set; }
        public Nullable<bool> IsAnswered { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
