//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunActivityApp.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string FullName { get; set; }
        public string ProfilImage { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string Team { get; set; }
        public string Role { get; set; }
        public string Location { get; set; }
        public string Address { get; set; }
        public string Hobbies { get; set; }
        public string Skillsets { get; set; }
    }
}
